# Example config for a DU with one 10MHz FDD cell using a USRP as RF frontend.
f1ap:
  cu_cp_addr: 127.0.10.1
  bind_addr: 127.0.10.2

f1u:
  socket:
    -
      bind_addr: 127.0.10.2

ru_sdr:
  device_driver: uhd
  device_args: type=b200,num_recv_frames=64,num_send_frames=64
#  srate: 11.52
  srate: 23.04

  otw_format: sc12  
  tx_gain: 50
  rx_gain: 30

cell_cfg:
  #dl_arfcn: 368500
  dl_arfcn: 622000
  #band: 3
  band: 78
  #channel_bandwidth_MHz: 10
  channel_bandwidth_MHz: 20
  common_scs: 30
  plmn: "00101"
  tac: 100
  pci: 1

log:
  filename: /tmp/du.log
  all_level: info

pcap:
  mac_enable: false
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: false
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: false
  f1u_filename: /tmp/du_f1u.pcap
  e2ap_enable: true                 # Set to true to enable E2AP PCAPs.
  e2ap_du_filename: /tmp/gnb_du_e2ap.pcap        # Path where the DU E2AP PCAP is stored.

e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU instance)
  e2sm_kpm_enabled: true            # Enable KPM service module
  e2sm_rc_enabled: true             # Enable RC service module
  addr: 127.0.0.1                   # Connect to localhost since port 36421 is mapped to host
  #bind_addr: 127.0.0.100           # A local IP that the E2 agent binds to for traffic from the RIC. ONLY required if running the RIC on a separate machine. 
  port: 36421                       # E2AP port exposed from Docker container

metrics:
  layers:
    enable_rlc: true                # Enable RLC metrics
    enable_sched: true              # Enable DU scheduler metrics
  periodicity:
    du_report_period: 1000          # Set DU statistics report period to 1s
